apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-node-3-config
  labels:
    app: canopy-node
    node-id: "3"
data:
  config.json: |
    {
      "logLevel": "debug",
      "chainId": 1,
      "sleepUntil": 0,
      "rootChain": [
        {
          "chainId": 1,
          "url": "http://canopy-node-1.default.svc.cluster.local:50002"
        },
        {
          "chainId": 2,
          "url": "http://canopy-node-2.default.svc.cluster.local:40002"
        }
      ],
      "runVDF": false,
      "headless": false,
      "walletPort": "30000",
      "explorerPort": "30001",
      "rpcPort": "30002",
      "adminPort": "30003",
      "rpcURL": "http://localhost:30002",
      "adminRPCUrl": "http://localhost:30003",
      "timeoutS": 3,
      "dataDirPath": "/root/.canopy",
      "dbName": "canopy",
      "inMemory": false,
      "networkID": 1,
      "listenAddress": "0.0.0.0:9003",
      "externalAddress": "canopy-node-3.default.svc.cluster.local",
      "maxInbound": 21,
      "maxOutbound": 7,
      "trustedPeerIDs": null,
      "dialPeers": ["canopy-node-1.default.svc.cluster.local:9001", "canopy-node-2.default.svc.cluster.local:9001"],
      "bannedPeerIDs": null,
      "bannedIPs": null,
      "minimumPeersToStart": 0,
      "newHeightTimeoutMS": 4500,
      "electionTimeoutMS": 1500,
      "electionVoteTimeoutMS": 1500,
      "proposeTimeoutMS": 2500,
      "proposeVoteTimeoutMS": 4000,
      "precommitTimeoutMS": 2000,
      "precommitVoteTimeoutMS": 2000,
      "commitTimeoutMS": 2000,
      "roundInterruptTimeoutMS": 2000,
      "maxTotalBytes": 1000000,
      "maxTransactionCount": 5000,
      "individualMaxTxSize": 4000,
      "dropPercentage": 35,
      "metricsEnabled": true,
      "prometheusAddress": "0.0.0.0:9090"
    }
