apiVersion: v1
kind: Service
metadata:
  name: canopy-node-1
  labels:
    app: canopy-node
    node-id: "1"
spec:
  type: ClusterIP
  selector:
    app: canopy-node
    node-id: "1"
  ports:
    - name: wallet
      port: 50000
      targetPort: 50000
      protocol: TCP
    - name: explorer
      port: 50001
      targetPort: 50001
      protocol: TCP
    - name: rpc
      port: 50002
      targetPort: 50002
      protocol: TCP
    - name: admin
      port: 50003
      targetPort: 50003
      protocol: TCP
    - name: p2p
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
