apiVersion: v1
kind: Service
metadata:
  name: node-3
  labels:
    app: canopy-node
    node-id: "3"
spec:
  type: ClusterIP
  selector:
    app: canopy-node
    node-id: "3"
  ports:
    - name: wallet
      port: 30000
      targetPort: 30000
      protocol: TCP
    - name: explorer
      port: 30001
      targetPort: 30001
      protocol: TCP
    - name: rpc
      port: 30002
      targetPort: 30002
      protocol: TCP
    - name: admin
      port: 30003
      targetPort: 30003
      protocol: TCP
    - name: p2p
      port: 9003
      targetPort: 9003
      protocol: TCP
    - name: prometheus
      port: 9092
      targetPort: 9090
      protocol: TCP
