apiVersion: v1
kind: ConfigMap
metadata:
  name: node-3-keystore
  labels:
    app: canopy-node
    node-id: "3"
data:
  keystore.json: |
    {
      "addressMap": {
        "02cd4e5eb53ea665702042a6ed6d31d616054dc5": {
          "publicKey": "98d45087a99bcbfde91993502e77dde869d4485c3778fe46513958320da560823d56a0108f4cf3513393f4d561bc489b",
          "salt": "74f0112bcffc91215b6f6266acec38ca",
          "encrypted": "183444bb69d2693a892e90ef7ebca9167719113488e4e803f8e87603ea84ccb40c423bc72db7303e81d7d216368ed763",
          "keyAddress": "02cd4e5eb53ea665702042a6ed6d31d616054dc5",
          "keyNickname": "node_2"
        },
        "6f94783856d5ce46d24dd5946215086211d70776": {
          "publicKey": "abda38eb50fbe53db9e9c3b141c6a1ec54ad40a4840e34784c975da4ee175eb4c5dd10b6d759ae8fdf8bc22511bbd97b",
          "salt": "cfbafc41835a47660f822ee26112d2c6",
          "encrypted": "f18135d9509b41b5edc42e74d22396cba3f11fd8a5acae008a49b6e8bd3540a48f74c0d9e65872b922091286a531eee7",
          "keyAddress": "6f94783856d5ce46d24dd5946215086211d70776",
          "keyNickname": "node_3"
        },
        "851e90eaef1fa27debaee2c2591503bdeec1d123": {
          "publicKey": "b88a5928e54cbf0a36e0b98f5bcf02de9a9a1deba6994739f9160181a609f516eb702936a0cbf4c1f2e7e6be5b8272f2",
          "salt": "3bff15134210c811e308eaa9b7b6024c",
          "encrypted": "8b757090dfc98bfbff4f5972f0ae4bb0339a82a753f633cd37aa921955d76cda6a5f521120e7559eb57f497e88f7f555",
          "keyAddress": "851e90eaef1fa27debaee2c2591503bdeec1d123",
          "keyNickname": "node_1"
        }
      },
      "nicknameMap": {
        "node_1": "851e90eaef1fa27debaee2c2591503bdeec1d123",
        "node_2": "02cd4e5eb53ea665702042a6ed6d31d616054dc5",
        "node_3": "6f94783856d5ce46d24dd5946215086211d70776"
      }
    }
  validator_key.json: |
    "3e9eb7a46defde2fa42dc74d85d0ee8cebaf327efa24b972e97b54af38d6e602"
  book.json: |
    {
      "book": [],
      "bookSize": 0
    }
  polls.json: |
    {
      "activePolls": {
        "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c": {
          "6f94783856d5ce46d24dd5946215086211d70776": true
        }
      },
      "pollMeta": {
        "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c": {
          "startPoll": "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c",
          "url": "https://forum.cnpy.network/something",
          "endHeight": 1000000000000
        }
      }
    }
  proposals.json: |
    {
      "7edaf1a0cac74c54b9ec34023af7fe8977fe36b95e40f4566db12b6f69daf75c": {
        "proposal": {
          "type": "changeParameter",
          "msg": {
            "parameterSpace": "cons|fee|val|gov",
            "parameterKey": "protocolVersion",
            "parameterValue": "example",
            "startHeight": 1,
            "endHeight": 1000,
            "signer": "4646464646464646464646464646464646464646",
            "proposalHash": ""
          },
          "signature": {
            "publicKey": "95ecf39914b027b32132a8e24ad0e7d7a3599dcd06757b9eacf4cab391ea1fd7e3facde205d949a6e147402c81f90b6f",
            "signature": "923396da659a35c81b4600853d1f151126f1b322d82fe36bea50c978abbb99b7a20867ec33cc97649f46d58572e87b8a0c3a108a146265163410d4ac03555515a15096446479d9983edb492d26e6ff3f2e464657179692c12498e5cc5426b7f3"
          },
          "time": 1741350747491943,
          "createdHeight": 1,
          "fee": 10000,
          "memo": "example",
          "networkID": 1,
          "chainID": 1
        },
        "approve": true
      }
    }
