apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-node-keystore
data:
  keystore.json: |
    {
      "addressMap": {
        "31c019699f5eac8edf96db5de102c222b3f04ee6": {
          "publicKey": "85ecd385d99b690a344f79ea2c438024d203e6d9f3e7a13eac13835ce8b11b36ac7f7f1bd3c1b04ec077199a225f6005",
          "salt": "65784461f9589b9e519948b5cce78a66",
          "encrypted": "1154ffa5e66fb8ba964814e49712abf24bfa8d7103aff4fc3c5e72f4d74689fd6cc734672d48a4563d73fd810d47ce6a",
          "keyAddress": "31c019699f5eac8edf96db5de102c222b3f04ee6",
          "keyNickname": "test"
        },
        "a5d1e3bb22cf77a5d85b03e367f31270407056bb": {
          "publicKey": "84ee2d005cd1cb59cad31128548bae0de8e728c4e2431a75229b28d4a718c97d1da093ab29b670a662f843e97217d735",
          "salt": "e79cb66ee7726376833e4d2e75b133a7",
          "encrypted": "18352786dd56aad05911801fa4b3dc7931849dbbb5ac4029746d2bc040e454a4f86348fb8dec9f7eab1e39109fe7c757",
          "keyAddress": "a5d1e3bb22cf77a5d85b03e367f31270407056bb",
          "keyNickname": "test2"
        },
        "29d19c74ac51b199cc070181886bea5cad3f88c3": {
          "publicKey": "95d857490295d5d55a2f25e442778eb7aaac33712cb2a92dd62843c98e6665d52a3dc51eabccaf7bb121492ef3f347fe",
          "salt": "d19185a8a8a7a12b885a7aeb6187895a",
          "encrypted": "a2732e5021c377ad9797598f511e0636aefbc868d4d5ab98f8c5e8d50b5ff0ab5d198e8b51dce72a47cb7558cf94bc05",
          "keyAddress": "29d19c74ac51b199cc070181886bea5cad3f88c3",
          "keyNickname": "test3"
        }
      },
      "nicknameMap": {
        "test": "31c019699f5eac8edf96db5de102c222b3f04ee6",
        "test2": "a5d1e3bb22cf77a5d85b03e367f31270407056bb",
        "test3": "29d19c74ac51b199cc070181886bea5cad3f88c3"
      }
    }
  validator_key.json: |
    "303546fc92d46d510c6cb2e84e6fe8b8a1fb5bf53daec7fa5e5f1893cb7992da"
  book.json: |
    {
      "book": [],
      "bookSize": 0
    }
  proposals.json: |
    {
      "dc535d9961e9df7d16dd163d7a054792cf824dabe9aa37a525ca9e45bf27211d": {
        "proposal": {
          "type": "changeParameter",
          "msg": {
            "parameterSpace": "cons|fee|val|gov",
            "parameterKey": "protocolVersion",
            "parameterValue": "example",
            "startHeight": 1,
            "endHeight": 1000,
            "signer": "4646464646464646464646464646464646464646"
          },
          "signature": {
            "publicKey": "b24a8cd055a6d7eb18ddb3d42c722a3e21ad4a6903fcf524c9f854eda8c415033b0c4056584dcbd51b0f912637a7f12d",
            "signature": "845c5963d488310e990aae9c6fd4f6f306d783c0ecc59929d2a9ab0e42a62bc63ff4b5634ebc5c98f8b921ec2d37ca4911bd318452159c4d8aec631db4d0b46fdadd3cbdbb3e0efe96b69d6c11f6677575d8e736976d3ccae3b70e88ec54856b"
          },
          "time": 1760928580735837,
          "createdHeight": 1,
          "fee": 10000,
          "memo": "example",
          "networkID": 1,
          "chainID": 1
        },
        "approve": true
      }
    }
  polls.json: |
    {
      "activePolls": {
        "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c": {
          "31c019699f5eac8edf96db5de102c222b3f04ee6": true
        }
      },
      "pollMeta": {
        "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c": {
          "startPoll": "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c",
          "url": "https://forum.cnpy.network/something",
          "endHeight": 1000000000000
        }
      }
    }
