apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-node-keystore
data:
  keystore.json: |
    {
      "addressMap": {
        "29d19c74ac51b199cc070181886bea5cad3f88c3": {
          "publicKey": "95d857490295d5d55a2f25e442778eb7aaac33712cb2a92dd62843c98e6665d52a3dc51eabccaf7bb121492ef3f347fe",
          "salt": "d19185a8a8a7a12b885a7aeb6187895a",
          "encrypted": "a2732e5021c377ad9797598f511e0636aefbc868d4d5ab98f8c5e8d50b5ff0ab5d198e8b51dce72a47cb7558cf94bc05",
          "keyAddress": "29d19c74ac51b199cc070181886bea5cad3f88c3",
          "keyNickname": "test"
        },
        "a5d1e3bb22cf77a5d85b03e367f31270407056bb": {
          "publicKey": "84ee2d005cd1cb59cad31128548bae0de8e728c4e2431a75229b28d4a718c97d1da093ab29b670a662f843e97217d735",
          "salt": "e79cb66ee7726376833e4d2e75b133a7",
          "encrypted": "18352786dd56aad05911801fa4b3dc7931849dbbb5ac4029746d2bc040e454a4f86348fb8dec9f7eab1e39109fe7c757",
          "keyAddress": "a5d1e3bb22cf77a5d85b03e367f31270407056bb",
          "keyNickname": "test2"
        }
      },
      "nicknameMap": {
        "test": "29d19c74ac51b199cc070181886bea5cad3f88c3",
        "test2": "a5d1e3bb22cf77a5d85b03e367f31270407056bb"
      }
    }
  validator_key.json: |
    "52f3a89cbf53761b1b2e9788181153ceee7cf28d4abc4897caaf101f77871a13"
  book.json: |
    {
      "book": [],
      "bookSize": 0
    }
  proposals.json: |
    {
      "c03122e148752578a3fcd4e142000dd500dc93f452033c2fa2ab1aaf9d2d6be5": {
        "proposal": {
          "type": "changeParameter",
          "msg": {
            "parameterSpace": "cons|fee|val|gov",
            "parameterKey": "protocolVersion",
            "parameterValue": "example",
            "startHeight": 1,
            "endHeight": 1000,
            "signer": "4646464646464646464646464646464646464646"
          },
          "signature": {
            "publicKey": "89d282fcc9d7f3d13c9b50971183ce55a9613f3467123002f18588a9b3d1365600739e9b7a9c234b14c3c10a756b9218",
            "signature": "84fcac4e33098e54a9966b8e6eaa08b548dd999be8df0ff72c4e2a6206d13052f76a6d3e2f7df50cb9a280b53fe60f56023bc73b802c87cb5d3ddefd8f11a017684eccba635876b9169782a2520d01c73da9582cff5629386f6ed9dfae84595e"
          },
          "time": 1760396730063385,
          "createdHeight": 1,
          "fee": 10000,
          "memo": "example",
          "networkID": 1,
          "chainID": 1
        },
        "approve": true
      }
    }
  polls.json: |
    {
      "activePolls": {
        "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c": {
          "29d19c74ac51b199cc070181886bea5cad3f88c3": true
        }
      },
      "pollMeta": {
        "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c": {
          "startPoll": "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c",
          "url": "https://forum.cnpy.network/something",
          "endHeight": 1000000000000
        }
      }
    }