apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-node-config
data:
  config.json: |
    {
      "logLevel": "info",
      "chainId": 1,
      "sleepUntil": 0,
      "rootChain": [
        {
          "chainId": 1,
          "url": "http://localhost:50002"
        }
      ],
      "runVDF": true,
      "headless": false,
      "autoUpdate": false,
      "level": 0,
      "logStructured": false,
      "logJSON": false,
      "Out": null,
      "walletPort": "50000",
      "explorerPort": "50001",
      "rpcPort": "50002",
      "adminPort": "50003",
      "rpcURL": "http://localhost:50002",
      "adminRPCUrl": "http://localhost:50003",
      "timeoutS": 3,
      "dataDirPath": "/root/.canopy",
      "dbName": "canopy",
      "indexByAccount": true,
      "inMemory": false,
      "cleanupBlockInterval": 108,
      "networkID": 1,
      "listenAddress": "0.0.0.0:9001",
      "externalAddress": "",
      "maxInbound": 21,
      "maxOutbound": 7,
      "trustedPeerIDs": null,
      "dialPeers": null,
      "bannedPeersIDs": null,
      "bannedIPs": null,
      "minimumPeersToStart": 0,
      "newHeightTimeoutMS": 4500,
      "electionTimeoutMS": 1500,
      "electionVoteTimeoutMS": 1500,
      "proposeTimeoutMS": 2500,
      "proposeVoteTimeoutMS": 4000,
      "precommitTimeoutMS": 2000,
      "precommitVoteTimeoutMS": 2000,
      "commitTimeoutMS": 2000,
      "roundInterruptTimeoutMS": 0,
      "maxTotalBytes": 10000000,
      "maxTransactionCount": 5000,
      "individualMaxTxSize": 4000,
      "dropPercentage": 35,
      "lazyMempoolCheckFrequencyS": 1,
      "metricsEnabled": true,
      "prometheusAddress": "0.0.0.0:9090"
    }