apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-config.yaml
  - configmap-genesis.yaml
  - configmap-keystore.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml